// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_ActionIndicatorsMZ","status":true,"description":"(v.1.0) Display an icon when the player is able to interact with an event. View help for comment tag.","parameters":{"yOffset":"-10","zPosition":"5","autoHide":"true","iconOpacity":"200"}},
{"name":"Cae_TitleMenu","status":true,"description":"v1.1 - Customise title screen commands and layout.","parameters":{"New Game Commands":"[]","Max No-Scroll Commands":"0","Block Style":"false","JS: Block Width":"Graphics.boxWidth * 0.8","--- Advanced ---":"","New Game Symbol":"altStart%1"}},
{"name":"GabeMZ_StepSound","status":true,"description":"[v1.1.1] Allows characters to emit step sounds when walking.","parameters":{"stepSoundSettings":"[\"{\\\"baseName\\\":\\\"SciFiAmbience\\\",\\\"variance\\\":\\\"1\\\",\\\"volume\\\":\\\"75\\\",\\\"volumeVariance\\\":\\\"0\\\",\\\"pitch\\\":\\\"100\\\",\\\"pitchVariance\\\":\\\"0\\\",\\\"pan\\\":\\\"0\\\",\\\"panVariance\\\":\\\"0\\\"}\"]","playerStepSound":"true","followersStepSound":"true","walkingFrequency":"100","dashingFrequency":"90"}}
];
